import type { CustomerOrderDetail } from "./types";

/**
 * Isolated mock customer orders for UI development and preview.
 * This file is strictly separated so it can be swapped out by the real API service
 * without changing any UI components or pages.
 */
export const mockCustomerOrders: CustomerOrderDetail[] = [
  {
    id: "ord_001",
    orderNumber: "ORD-1025",
    status: "pending",
    subtotal: 620,
    gst: 31,
    deliveryCharge: 40,
    total: 691,
    paymentStatus: "success",
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(), // 10 mins ago
    itemCount: 2,
    items: [
      {
        id: "item_1",
        name: "Paneer Tikka Butter Masala",
        quantity: 1,
        price: 380,
        lineTotal: 380,
        imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=300&auto=format&fit=crop&q=60",
      },
      {
        id: "item_2",
        name: "Garlic Butter Naan (2 pcs)",
        quantity: 2,
        price: 120,
        lineTotal: 240,
      },
    ],
    address: {
      label: "Home",
      building: "Flat 402, Sunrise Heights",
      street: "MG Road, Indiranagar",
      area: "Indiranagar 1st Stage",
      city: "Bengaluru",
      landmark: "Near BDA Complex",
      instructions: "Ring doorbell twice, leave at door if no answer.",
    },
    specialInstructions: "Please make the gravy mildly spicy and provide extra green chutney.",
  },
  {
    id: "ord_002",
    orderNumber: "ORD-1024",
    status: "preparing",
    subtotal: 890,
    gst: 44.5,
    deliveryCharge: 0,
    total: 934.5,
    paymentStatus: "success",
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(), // 35 mins ago
    itemCount: 3,
    items: [
      {
        id: "item_3",
        name: "Wood-Fired Margherita Pizza",
        quantity: 1,
        price: 450,
        lineTotal: 450,
        imageUrl: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=300&auto=format&fit=crop&q=60",
      },
      {
        id: "item_4",
        name: "Creamy Truffle Mushroom Pasta",
        quantity: 1,
        price: 320,
        lineTotal: 320,
      },
      {
        id: "item_5",
        name: "Crispy Garlic Bread",
        quantity: 1,
        price: 120,
        lineTotal: 120,
      },
    ],
    address: {
      label: "Work",
      building: "Tower B, 5th Floor",
      street: "Embassy Tech Village, Outer Ring Road",
      area: "Devarabisanahalli",
      city: "Bengaluru",
      landmark: "Opposite Cisco Campus",
    },
    specialInstructions: "Please make the crust extra crispy.",
  },
  {
    id: "ord_003",
    orderNumber: "ORD-1023",
    status: "accepted",
    subtotal: 480,
    gst: 24,
    deliveryCharge: 30,
    total: 534,
    paymentStatus: "pending",
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(), // 20 mins ago
    itemCount: 2,
    items: [
      {
        id: "item_6",
        name: "Classic Cheese Gourmet Burger",
        quantity: 1,
        price: 280,
        lineTotal: 280,
        imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&auto=format&fit=crop&q=60",
      },
      {
        id: "item_7",
        name: "Seasoned Peri Peri Fries",
        quantity: 1,
        price: 200,
        lineTotal: 200,
      },
    ],
    address: {
      label: "Home",
      building: "Villa 12, Green Glen Layout",
      street: "Sarjapur Main Road",
      area: "Bellandur",
      city: "Bengaluru",
      landmark: "Near Central Mall",
    },
  },
  {
    id: "ord_004",
    orderNumber: "ORD-1021",
    status: "delivered",
    subtotal: 720,
    gst: 36,
    deliveryCharge: 0,
    total: 756,
    paymentStatus: "success",
    createdAt: "2026-09-08T14:35:00.000Z", // Yesterday
    itemCount: 2,
    items: [
      {
        id: "item_8",
        name: "Hyderabadi Dum Biryani (Paneer)",
        quantity: 1,
        price: 420,
        lineTotal: 420,
        imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=300&auto=format&fit=crop&q=60",
      },
      {
        id: "item_9",
        name: "Gulab Jamun with Rabri (2 pcs)",
        quantity: 1,
        price: 300,
        lineTotal: 300,
      },
    ],
    address: {
      label: "Home",
      building: "Flat 402, Sunrise Heights",
      street: "MG Road, Indiranagar",
      area: "Indiranagar 1st Stage",
      city: "Bengaluru",
    },
    specialInstructions: "Delivered directly to customer. Thank you for ordering!",
  },
  {
    id: "ord_005",
    orderNumber: "ORD-1020",
    status: "cancelled",
    subtotal: 540,
    gst: 27,
    deliveryCharge: 40,
    total: 607,
    paymentStatus: "refunded",
    createdAt: "2026-09-07T11:20:00.000Z",
    itemCount: 2,
    items: [
      {
        id: "item_10",
        name: "Spicy Arrabbiata Penne Pasta",
        quantity: 1,
        price: 340,
        lineTotal: 340,
      },
      {
        id: "item_11",
        name: "Cheesy Garlic Sticks",
        quantity: 1,
        price: 200,
        lineTotal: 200,
      },
    ],
    address: {
      label: "Home",
      building: "Flat 402, Sunrise Heights",
      street: "MG Road, Indiranagar",
      area: "Indiranagar 1st Stage",
      city: "Bengaluru",
    },
    cancellationReason: "Ordered by mistake, placed a revised order immediately.",
  },
  {
    id: "ord_006",
    orderNumber: "ORD-1019",
    status: "declined",
    subtotal: 1150,
    gst: 57.5,
    deliveryCharge: 0,
    total: 1207.5,
    paymentStatus: "refunded",
    createdAt: "2026-09-06T19:45:00.000Z",
    itemCount: 3,
    items: [
      {
        id: "item_12",
        name: "Family Feast Combo",
        quantity: 1,
        price: 950,
        lineTotal: 950,
      },
      {
        id: "item_13",
        name: "Chocolate Lava Cake",
        quantity: 2,
        price: 100,
        lineTotal: 200,
      },
    ],
    address: {
      label: "Home",
      building: "Flat 402, Sunrise Heights",
      street: "MG Road, Indiranagar",
      area: "Indiranagar 1st Stage",
      city: "Bengaluru",
    },
    declineReason: "Kitchen closed early due to heavy rainstorm and local power outage. Full refund issued.",
  },
];
