import type { AdminOrder, AdminCustomer } from "./types";

export const adminOrders: AdminOrder[] = [
  {
    id: "#ORD-1024",
    customerName: "Rahul Verma",
    items: 2,
    amount: 598,
    status: "Preparing",
    orderDate: "Today, 12:42 PM",
  },
  {
    id: "#ORD-1023",
    customerName: "Priya Sharma",
    items: 3,
    amount: 849,
    status: "Pending",
    orderDate: "Today, 12:28 PM",
  },
  {
    id: "#ORD-1022",
    customerName: "Aman Singh",
    items: 1,
    amount: 299,
    status: "Ready",
    orderDate: "Today, 12:15 PM",
  },
  {
    id: "#ORD-1021",
    customerName: "Neha Gupta",
    items: 4,
    amount: 1120,
    status: "Completed",
    orderDate: "Today, 11:54 AM",
  },
  {
    id: "#ORD-1020",
    customerName: "Arjun Das",
    items: 2,
    amount: 549,
    status: "Cancelled",
    orderDate: "Today, 11:37 AM",
  },
  {
    id: "#ORD-1019",
    customerName: "Sneha Roy",
    items: 3,
    amount: 720,
    status: "Confirmed",
    orderDate: "Today, 11:21 AM",
  },
  {
    id: "#ORD-1018",
    customerName: "Vikram Shah",
    items: 2,
    amount: 480,
    status: "Preparing",
    orderDate: "Today, 11:05 AM",
  },
];

export const adminCustomers: AdminCustomer[] = [
  {
    id: "CUST-001",
    name: "Rahul Verma",
    email: "rahul.verma@example.com",
    phone: "+91 98765 43210",
    totalOrders: 14,
    totalSpent: 8420,
    joinedDate: "Jan 15, 2026",
  },
  {
    id: "CUST-002",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    phone: "+91 98123 45678",
    totalOrders: 22,
    totalSpent: 14250,
    joinedDate: "Feb 02, 2026",
  },
  {
    id: "CUST-003",
    name: "Aman Singh",
    email: "aman.singh@example.com",
    phone: "+91 97654 32109",
    totalOrders: 8,
    totalSpent: 4890,
    joinedDate: "Mar 10, 2026",
  },
  {
    id: "CUST-004",
    name: "Neha Gupta",
    email: "neha.gupta@example.com",
    phone: "+91 99887 76655",
    totalOrders: 31,
    totalSpent: 21800,
    joinedDate: "Dec 18, 2025",
  },
  {
    id: "CUST-005",
    name: "Arjun Das",
    email: "arjun.das@example.com",
    phone: "+91 95432 10987",
    totalOrders: 5,
    totalSpent: 3120,
    joinedDate: "Apr 05, 2026",
  },
];